[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
encrypted_wheel = "FGJU8MoGAm61LQNZekvMhacoVPzmvcjh16kXaTbqqbM6"

[programs.devnet]
encrypted_wheel = "FGJU8MoGAm61LQNZekvMhacoVPzmvcjh16kXaTbqqbM6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=0ae54321-3384-4f6d-9fd0-32eba15976f2"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
